# Numpy Basics <hr style="border:2.5px solid #B57EDC"></hr>

Data Analyst: Jade Solomon D. Melarin <br>
Department: Electrical Engineering

In [10]:
# imports and packages
import numpy as np
from scipy import stats

# 1D Array

In [25]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

# 2D Array

In [34]:
my_array = np.array([
    [1,2,3],[4,5,6]
    ])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
my_array . T 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
np.sum(my_array,axis=0)

array([5, 7, 9])

In [40]:
#by column
np.sum(my_array,axis=1)

array([ 6, 15])

# Measures of central tendency

In [3]:
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [7]:
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [8]:
median_fruits = np.median(fruits)
median_fruits

np.float64(120.0)

In [11]:
mode_fruits = stats.mode(fruits)
mode_fruits

ModeResult(mode=np.int64(60), count=np.int64(1))

# Execise
# Jaguar vs Panther

# Jaguar

In [12]:
jaguar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])

In [16]:
jaguar_mean = np.mean(jaguar)
jaguar_mean

np.float64(9.399999999999999)

In [18]:
jaguar_median = np.median(jaguar)
jaguar_median

np.float64(9.8)

In [19]:
jaguar_mode = stats.mode(jaguar)
jaguar_mode

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [42]:
# population std
np.std(jaguar)

np.float64(2.101947149236112)

In [43]:
# sample std
np.std(jaguar, ddof=1)

np.float64(2.2045407685048604)

In [61]:
max_jaguar = np.max(jaguar)
min_jaguar = np.min(jaguar)

range_jaguar = max_jaguar - min_jaguar
range_jaguar

np.float64(8.0)

In [64]:
q1_jaguar = np.percentile(jaguar,25)
q1_jaguar


np.float64(9.4)

In [57]:
q2_jaguar = np.percentile(jaguar,50)
q2_jaguar

np.float64(9.8)

In [58]:
q3_jaguar = np.percentile(jaguar,75)
q3_jaguar

np.float64(10.45)

In [59]:
IQR = q3_jaguar - q1_jaguar
IQR

np.float64(1.049999999999999)

# panther

In [24]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])

In [20]:
panther_mean = np.mean(panther)
panther_mean

np.float64(10.75)

In [21]:
panther_median = np.median(panther)
panther_median

np.float64(9.55)

In [22]:
panther_mode = stats.mode(panther)
panther_mode

ModeResult(mode=np.float64(9.1), count=np.int64(3))

In [44]:
# population std
np.std(panther)

np.float64(3.1582431825304393)

In [45]:
# sample std
np.std(panther, ddof=1)

np.float64(3.3290806204983645)

In [63]:
max_panther = np.max(panther)
min_panther = np.min(panther)

range_panther = max_panther - min_panther
range_panther

np.float64(10.9)

In [65]:
q1_panther = np.percentile(panther,25)
q1_panther

np.float64(9.125)

In [68]:
q2_panther = np.percentile(panther,50)
q2_panther

np.float64(9.55)

In [69]:
q3_panther = np.percentile(panther,75)
q3_panther

np.float64(10.625)